name: GitHub Actions Test
run-name: ${{ github.actor }} is trying to pull
on:
  push:
    branches:
      - "main"
jobs:
  deploy-job:
    runs-on: self-hosted
    steps:
      - name: pull from repo
        env:
          PROJECT_PATH: ${{secrets.PROJECT_PATH}}
          PROJECTS_PATH: ${{secrets.PROJECTS_PATH}}
        run: |
          printenv -0 > test
          echo $PROJECTS_PATH > secret
          echo 
          if [ ! -d "$PROJECT_PATH" ]; then
            cd "$PROJECTS_PATH"
            git clone https://github.com/guillermoVicenteGonzalez/react-wumpus.git
          fi
          cd "$PROJECT_PATH"
          git pull -q --force

      - name: build docker
        env:
          PROJECT_PATH: ${{secrets.PROJECT_PATH}}
        run: |
          cd "$PROJECT_PATH"
          docker compose up
